// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from './routes/_404.tsx';
import * as $_app from './routes/_app.tsx';
import * as $accounts_accountId_transactions from './routes/accounts/[accountId]/transactions.tsx';
import * as $dashboard from './routes/dashboard.tsx';
import * as $index from './routes/index.tsx';
import * as $Carousel from './islands/Carousel.tsx';
import * as $DashboardSummary from './islands/DashboardSummary.tsx';
import * as $TransactionList from './islands/TransactionList.tsx';
import type { Manifest } from '$fresh/server.ts';

const manifest = {
  routes: {
    './routes/_404.tsx': $_404,
    './routes/_app.tsx': $_app,
    './routes/accounts/[accountId]/transactions.tsx': $accounts_accountId_transactions,
    './routes/dashboard.tsx': $dashboard,
    './routes/index.tsx': $index,
  },
  islands: {
    './islands/Carousel.tsx': $Carousel,
    './islands/DashboardSummary.tsx': $DashboardSummary,
    './islands/TransactionList.tsx': $TransactionList,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
