name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key.outputs.value }}

    steps:
      - uses: actions/checkout@v4

      - name: Generate cache key
        id: cache-key
        run: echo "value=${{ runner.os }}-deno-${{ hashFiles('**/deno.json', 'import_map.json', '**/deps.ts') }}" >> $GITHUB_OUTPUT

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.2.6

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/deno
            ~/.deno
          key: ${{ steps.cache-key.outputs.value }}
          restore-keys: |
            ${{ runner.os }}-deno-

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.2.6

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/deno
            ~/.deno
          key: ${{ needs.setup.outputs.cache-key }}
          restore-keys: |
            ${{ runner.os }}-deno-

      # Pre-populate cache with import map dependencies
      - name: Cache warmup
        run: deno cache --reload import_map.json

      - name: Check formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      # - name: Check types
      #   run: deno task check

  test:
    needs: [setup, build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.2.6

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/deno
            ~/.deno
          key: ${{ needs.setup.outputs.cache-key }}
          restore-keys: |
            ${{ runner.os }}-deno-

      - name: Start database
        run: docker compose up -d

      - name: Wait for database
        run: timeout 30s bash -c 'until docker compose exec -T db pg_isready; do sleep 1; done'

      - name: Run migrations
        run: deno run --env-file=.env.test backend:migrate

      - name: Run seed
        run: deno run --env-file=.env.test backend:seed

      - name: Run tests
        run: deno run --env-file=.env.test test

      - name: Generate coverage report
        run: deno task coverage

      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          fail_ci_if_error: true

      - name: Stop database
        if: always()
        run: docker compose down

  deploy:
    needs: [setup, build, test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    permissions:
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.2.6

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/deno
            ~/.deno
          key: ${{ needs.setup.outputs.cache-key }}
          restore-keys: |
            ${{ runner.os }}-deno-

      - name: Upload Backend to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: 'welz-backend'
          entrypoint: 'apps/backend/src/main.ts'

      - name: Build Web project
        run: deno task web:build

      - name: Upload Web to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: 'welz'
          entrypoint: 'apps/web/main.ts'
