name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start PostgreSQL with Docker Compose
        run: docker-compose up -d

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: '2.1.x'

      - name: Cache Deno dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/deps.ts') }}
          restore-keys: |
            ${{ runner.os }}-deno-

      - name: Check formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Wait for PostgreSQL
        timeout-minutes: 1
        run: |
          while ! docker-compose exec -T db pg_isready -U user; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 2
          done

      - name: Run backend migrations
        run: deno task backend:migrate

      - name: Run backend tests
        run: |
          deno task backend:test --coverage=coverage
          deno coverage ./coverage --lcov > coverage.lcov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.lcov
          fail_ci_if_error: true

      - name: Run web tests
        run: deno task web:test
